### ISSUE TITLE
Will you share the dataset split of  SCVD?

### ISSUE THREAD

**Issue by mortyzhou77** [Ti-Oluwanimi/Violence_Detection_Main#2]

**Comment by tolusophy** [comment]
Thanks for the interest in the dataset. In the [link](https://drive.google.com/file/d/16Uk5AAWo6UorGyQ_YaUUn6CWxPxMHE0K/view?usp=sharing), you will find the original dataset (with all videos converted to the avi format and splitted), as well as the augmented one (consistent time, avi format, splitted).
